#!/usr/bin/env python3

################################################################################
##                                                                            ##
##  This file is part of MCPL (see https://mctools.github.io/mcpl/)           ##
##                                                                            ##
##  Copyright 2015-2026 MCPL developers.                                      ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

#  Simple example showing how one can use the mcpl Python API to extract a
#  subset of particles from an existing MCPL file into a new smaller file, like
#  example_filtermcpl.c does with the C API. Particles are processed in blocks
#  of numpy arrays, which is efficient even for very large files.

import sys

import mcpl

infilename, outfilename = sys.argv[1:3]

#Open existing file and create output file. Transfer all meta-data from the
#existing file, and add an extra comment in the output file to document the
#process:
with mcpl.MCPLFile(infilename) as fi, mcpl.MCPLOutFile(outfilename) as fo:
    fo.transfer_metadata(fi)
    fo.hdr_add_comment('Applied filter for neutrons with ekin<0.1MeV')

    #Loop over blocks of particles from the input file. Indexing a block with a
    #boolean numpy array (a mask) gives a new block with just the selected
    #particles, which are then added to the output file. Their packed data is
    #transferred exactly, avoiding any lossy unpacking and repacking:
    for block in fi.particle_blocks:
        selected = block[ ( block.pdgcode == 2112 ) & ( block.ekin < 0.1 ) ]
        fo.add_particles( selected )

    #The same selection could also have been expressed as a string, which is
    #convenient when it is for instance provided by users of a script:
    #
    #    flt = mcpl.ParticleFilter('pdgcode == neutron && ekin < 0.1MeV')
    #    for block in fi.particle_blocks:
    #        fo.add_particles( block[ flt(block) ] )

#Note that any stat:sum:... statistics in the files will still be fine, since
#we only filtered the particles based on their properties. If we had instead
#selected particles based on their position in the file, we should have called
#fo.hdr_scale_stat_sums(scale) with an appropriate choice of scale. If a proper
#scale is too complicated to deduce, one can always use scale=-1.0 since this
#will mark all the statistics parameters as being unavailable (which is better
#than being silently misleading).
