#!/usr/bin/env python

###################################################################################
#                                                                                 #
#  Monte Carlo Particle Lists : MCPL                                              #
#                                                                                 #
#  Simple example with comments, showing how one can use the mcpl.py module to    #
#  access MCPL files.                                                             #
#                                                                                 #
#  Find more information and updates at https://mctools.github.io/mcpl/           #
#                                                                                 #
#  This file can be freely used as per the terms in the LICENSE file.             #
#                                                                                 #
#  Written by Thomas Kittelmann, 2017.                                            #
#                                                                                 #
###################################################################################

#Make this example work with both python2 and python3:
from __future__ import print_function

import sys, os

#Import mcpl module (with a fall-back sys.path edit, so the example can be run
#from an MCPL installation even though the user did not set PYTHONPATH correctly):
try:
    import mcpl
except ImportError:
    try:
        sys.path.insert(0,os.path.join(os.path.dirname(__file__),'..','python'))
        import mcpl
    except ImportError:
        sys.path.insert(0,os.path.join(os.path.dirname(__file__),'..','src','python'))
        import mcpl


#Get name of input file to open from command line:
inputfile = sys.argv[1]

#Uncomment next line for module documentation:
#help(mcpl)

#Open the file:
f = mcpl.MCPLFile(inputfile)

#Dump entire header to stdout:
f.dump_hdr()

#Or access relevant parts:
print( 'Number of particles in file: %i' % f.nparticles )
print( 'Numbers are in single-precision: %s' % f.opt_singleprec )
for c in f.comments:
    print( "Some comment: %s" % c )

#Loop over all particles and print their positions and energies:
for p in f.particles:
    print( p.x, p.y, p.z, p.ekin )
    #help(p) #<-- uncomment to see all field names

#Same, but each iteration will be over a big "block" of 10000 particles, so all
#fields are now numpy arrays of length 10000:

for p in f.particle_blocks:
    print( p.x, p.y, p.z, p.ekin )

#NB: change blocklength to, say, 1000, by opening file with:
#    mcpl.MCPLFile('example.mcpl',blocklength=1000)
