#!/usr/bin/env python3

################################################################################
##                                                                            ##
##  This file is part of MCPL (see https://mctools.github.io/mcpl/)           ##
##                                                                            ##
##  Copyright 2015-2026 MCPL developers.                                      ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

#  Simple example with comments, showing how one can use the mcpl Python API to
#  access MCPL files.

import mcpl
import sys

#Get name of input file to open from command line:
inputfile = sys.argv[1]

#Uncomment next line for module documentation:
#help(mcpl)

#Open the file:
f = mcpl.MCPLFile(inputfile)

#Dump entire header to stdout:
f.dump_hdr()

#Or access relevant parts:
print( 'Number of particles in file: %i' % f.nparticles )
print( 'Numbers are in single-precision: %s' % f.opt_singleprec )
for c in f.comments:
    print( "Some comment: %s" % c )

#Loop over all particles and print their positions and energies:
for p in f.particles:
    print( p.x, p.y, p.z, p.ekin )
    #help(p) #<-- uncomment to see all field names

#Same, but each iteration will be over a big "block" of 10000 particles, so all
#fields are now numpy arrays of length 10000:

for p in f.particle_blocks:
    print( p.x, p.y, p.z, p.ekin )

#NB: change blocklength to, say, 1000, by opening file with:
#    mcpl.MCPLFile('example.mcpl',blocklength=1000)
